### ISSUE TITLE
Can't select current folder while inside

### ISSUE THREAD

**Issue by EmperorCookie** [Araxeus/ls-interactive#49]
There is no way to use the `alt`+`enter` shortcut to echo current folder. As a workaround, I find myself having to navigate further down and press `alt`+`enter` on the `..` entry.

I would suggest adding the `.` entry, or providing a new shortcut to select the current location.

**Comment by Araxeus** [comment]
Any proposal for a shortcut?

A `.` entry is a bit much in my opinion.

I also have another Idea, could make `shit`/`alt` + `enter` on the `..` entry echo the current folder instead of its parent?

It would be a bit counterintuitive but you could just press Left Arrow then the shortcut to get the previous effect

**Comment by EmperorCookie** [comment]
More intuitive than you think because pressing `alt`+`enter` on the `..` entry was the first thing that I tried.

**Comment by Araxeus** [comment]
Thank you for the suggestion, it was added in https://github.com/Araxeus/ls-interactive/releases/tag/v1.7.0

(You can now also download ls-interactive from cargo, if you have rust installed on your pc)

**Comment by EmperorCookie** [comment]
Thank you for implementing this! It's much easier to use now!

**Comment by jackusay** [comment]
so how to stay in current folder while inside?
